export default {
    "http://ihe-d.de/CodeSystems/ProzessrollenFuerAutoren": {
        1: "Einweiser",
        2: "Entlassender",
        3: "Überweiser",
        4: "Durchführender",
        5: "durchführendes Gerät",
        6: "Betreuer",
        7: "Pflegender",
        8: "Behandler",
        9: "Erstbehandler außerhalb einer Einrichtung",
        10: "Bereitstellender",
        11: "Dokumentierender",
        12: "dokumentierendes Gerät",
        13: "Validierer",
        14: "Gesetzlich Verantwortlicher",
        15: "Beratender",
        16: "Informierender",
        17: "Begutachtender",
    },
    "http://ihe-d.de/CodeSystems/PatientenbeziehungsrollenFuerAutoren": {
        101: "Hausarzt",
        102: "Patient",
        103: "Arbeitgebervertreter",
        104: "Primärbetreuer (langfristig)",
        105: "Kostenträgerverteter",
    },
    "urn:oid:1.2.276.0.76.5.114": {
        10: "FA Allgemeinmedizin",
        20: "FA Anästhesiologie",
        30: "FA Augenheilkunde",
        50: "FA Frauenheilkunde und Geburtshilfe",
        60: "FA Hals-, Nasen-, Ohrenheilkunde",
        70: "FA Haut- und Geschlechtskrankheiten",
        80: "FA Innere Medizin",
        91: "SP Kinderkardiologie",
        93: "SP Neonatologie",
        102: "FA Kinder- und Jugendpsychiatrie und -psychotherapie",
        110: "FA Laboratoriumsmedizin",
        130: "FA Mund-Kiefer-Gesichts-Chirurgie",
        142: "FA Neurologie",
        147: "FA Psychiatrie und Psychotherapie",
        150: "FA Neurochirurgie",
        170: "FA Pathologie",
        180: "FA Pharmakologie und Toxikologie",
        196: "SP Kinderradiologie",
        197: "SP Neuroradiologie",
        200: "FA Urologie",
        210: "FA Arbeitsmedizin",
        220: "FA Nuklearmedizin",
        230: "FA Öffentliches Gesundheitswesen",
        240: "FA Rechtsmedizin",
        250: "FA Hygiene und Umweltmedizin",
        271: "FA Neuropathologie",
        281: "FA Klinische Pharmakologie",
        291: "FA Strahlentherapie",
        301: "FA Anatomie",
        302: "FA Biochemie",
        303: "FA Transfusionsmedizin",
        304: "FA Kinderchirurgie",
        308: "FA Physiologie",
        313: "FA Herzchirurgie",
        314: "FA Humangenetik",
        330: "FA Physikalische und Rehabilitative Medizin",
        341: "FA Kinder- und Jugendmedizin",
        359: "Fachzahnarzt für Mikrobiologie",
        360: "Fachzahnarzt für Kieferchirurgie (§ 6 Abs. 1 BMV)",
        361: "Fachzahnarzt für theoretisch-experimentelle Medizin",
        511: "FA Gefäßchirurgie",
        512: "FA Orthopädie und Unfallchirurgie",
        513: "FA Thoraxchirurgie",
        514: "FA Visceralchirurgie",
        515: "SP Gynäkologische Onkologie",
        516: "SP Gynäkologische Endokrinologie und Reproduktionsmedizin",
        517: "SP Spezielle Geburtshilfe und Perinatalmedizin",
        518: "FA Sprach-, Stimm- und kindliche Hörstörungen",
        521: "FA Innere Medizin und (SP) Angiologie",
        522: "FA Innere Medizin und (SP) Endokrinologie und Diabetologie",
        523: "FA Innere Medizin und (SP) Gastroenterologie",
        524: "FA Innere Medizin und (SP) Hämatologie und Onkologie",
        525: "FA Innere Medizin und (SP) Kardiologie",
        526: "FA Innere Medizin und (SP) Nephrologie",
        527: "FA Innere Medizin und (SP) Pneumologie",
        528: "FA Innere Medizin und (SP) Rheumatologie",
        530: "SP Kinder-Hämatologie und -Onkologie",
        531: "SP Neuropädiatrie",
        532: "FA Mikrobiologie, Virologie und Infektionsepidemiologie",
        533: "SP Forensische Psychiatrie",
        534: "FA Psychosomatische Medizin und Psychotherapie",
        535: "FA Radiologie (neue (M-)WBO)",
        542: "FA Plastische und Ästhetische Chirurgie",
        544: "FA Allgemeinchirurgie",
    },
    "http://ihe-d.de/CodeSystems/QualifikationenNichtAerztlicherAutoren": {
        1: "Gesundheits- Sozial-, Sportmanagement",
        2: "Arzthilfe, Praxisorganisation, -verwaltung",
        3: "Kaufmann/-frau - Gesundheitswesen",
        4: "Medizinischer Fachangestellter",
        6: "Zahnmedizinischer Fachangestellter",
        7: "Arztsekretär",
        8: "Sozial-, Gesundheitsmanagement",
        9: "Gesundheitsaufseher / Hygienekontrolleur",
        10: "Assistent Gesundheits- und Sozialwesen",
        11: "Beamte Sozialversicherung",
        12: "Beamte Sozialverwaltung",
        13: "Betriebswirt Sozialversicherung",
        14: "Gesundheitsmanager",
        15: "Sozialökonom, -wirt",
        16: "Sozialversicherungsfachangestellte",
        17: "Sportmanagement",
        18: "Sportassistent",
        19: "Fachwirt Fitness",
        20: "Sport- und Fitnesskaufmann",
        21: "Sportmanager, Sportökonom",
        22: "nichtärztliche medizinische Analyse, Beratung, Pflege, Therapie",
        23: "Gesundheitsberatung, -förderung",
        24: "Assistenten für Gesundheitstourismus, -prophylaxe",
        25: "Diätassistent",
        26: "Gesundheitsförderer, -pädagoge",
        27: "Gesundheitswissenschaftler",
        28: "Oekotrophologe",
        29: "Tai-Chi-Chuan- und Qigong-Lehrer",
        30: "Yogalehrer",
        31: "Sportfachmann",
        32: "Sportwissenschaftler",
        33: "Kranken-, Altenpflege, Geburtshilfe",
        34: "Altenpflegehelfer",
        35: "Altenpfleger",
        36: "Fachkraft Pflegeassistenz",
        37: "Gesundheits- und Kinderkrankenpfleger",
        38: "Gesundheits- und Krankenpflegehelfer",
        39: "Gesundheits- und Krankenpfleger",
        40: "Haus- und Familienpfleger",
        41: "Hebamme / Entbindungspfleger",
        42: "Heilerziehungspfleger",
        43: "Helfer Altenpflege",
        44: "Helfer stationäre Krankenpflege",
        45: "Heilerziehungspflegehelfer",
        46: "Pflegewissenschaftler",
        47: "Nichtärztliche Behandlung, Therapie (außer Psychotherapie)",
        48: "Akademischer Sprachtherapeut",
        49: "Atem-, Sprech- und Stimmlehrer",
        50: "Ergotherapeut",
        51: "Fachangestellter für Bäderbetriebe",
        52: "Heilpraktiker",
        53: "Klinischer Linguist",
        54: "Kunsttherapeut",
        55: "Logopäde",
        56: "Masseur und medizinische Bademeister",
        57: "Motologe",
        58: "Musiktherapeut",
        59: "Orthoptist",
        60: "Physiotherapeut",
        61: "Podologe",
        62: "Sporttherapeut",
        63: "Sprechwissenschaftler",
        64: "Staatlich anerkannter Sprachtherapeut",
        65: "Stomatherapeut",
        66: "Tanz- und Bewegungstherapeut",
        68: "Sozialtherapeut",
        69: "Pharmazeutische Beratung, Pharmavertrieb",
        70: "Apotheker /Fachapotheker",
        71: "Pharmazeut",
        72: "Pharmazeutisch-technischer Assistent - PTA",
        73: "Pharmazeutisch-kaufmännischer Angestellter",
        74: "Psychologische Analyse, Beratung, Therapie",
        75: "Gesundheits- und Rehabilitationspsychologe",
        76: "Kinder- und Jugendpsychotherapeut",
        77: "Klinischer Psychologe",
        78: "Kommunikationspsychologe",
        79: "Pädagogischer Psychologe",
        80: "Psychoanalytiker",
        81: "Psychologe",
        82: "Psychologischer Psychotherapeut",
        83: "Sportpsychologe",
        84: "Verkehrspsychologe",
        85: "Wirtschaftspsychologe",
        86: "Rettungsdienst",
        87: "Ingenieur Rettungswesen",
        88: "Notfallsanitäter",
        89: "Rettungsassistent",
        90: "Rettungshelfer",
        91: "Rettungssanitäter",
        92: "med. Datenverarbeitung",
        94: "Medizinischer Dokumentar",
        95: "Medizinischer Dokumentationsassistent",
        173: "Fachangestellter f. Medien- und Informationsdienste - Medizinische Dokumentation",
        174: "Medizinischer Informationsmanager",
        96: "Soziales, Pädagogik",
        97: "Kinderbetreuung, -erziehung",
        98: "Pädagoge",
        99: "Kinderdorfmutter, -vater",
        100: "Kinderpfleger",
        101: "Erzieher",
        102: "Erzieher Jugend- und Heimerziehung",
        103: "Lehrer",
        104: "Orientierungs- und Mobilitätslehrer",
        105: "Medien-, Kulturpädagogik",
        106: "Musikpädagoge",
        107: "Sozialberatung, -arbeit",
        108: "Sozialarbeiter / Sozialpädagoge",
        109: "Betreuungskraft / Alltagsbegleiter",
        110: "Gerontologe",
        111: "Psychosozialer Prozessbegleiter",
        112: "Rehabilitationspädagoge",
        113: "Sozialassistent",
        114: "Seelsorge",
        115: "Religionspädagoge",
        116: "Gemeindehelfer, Gemeindediakon",
        117: "Theologe",
        118: "Medizintechnik, Laboranalyse",
        119: "Medizin-, Orthopädie- und Rehatechnik",
        120: "Assistent Medizinische Gerätetechnik",
        121: "Augenoptiker",
        122: "Hörakustiker / Hörgeräteakustiker",
        123: "Hörgeräteakustikermeister",
        124: "Ingenieur Augenoptik",
        125: "Ingenieur - Hörtechnik und Audiologie",
        126: "Ingenieur - Medizintechnik",
        127: "Ingenieur - Orthopädie- und Rehatechnik",
        128: "Medizinphysiker (z.B. in Strahlenmedizin)",
        129: "Orthopädieschuhmacher",
        130: "Orthopädietechnik-Mechaniker",
        131: "Zahntechniker",
        132: "Glasbläser (Fachrichtung Kunstaugen)",
        133: "staatlich geprüfter Techniker der Fachrichtung Medizintechnik",
        134: "Medizinisch-technische Assistenz",
        135: "Anästhesietechnischer Assistent",
        136: "HNO Audiologieassistent",
        137: "Medizinisch-Technischer Assistent Funktionsdiagnostik - MTA-F",
        138: "Medizinisch-Technischer Laboratoriumsassistent - MTA-L",
        139: "Medizinisch-Technischer Radiologieassistent - MTA-R",
        140: "Operationstechnischer Angestellter",
        141: "Operationstechnischer Assistent",
        143: "Zytologieassistent",
        144: "Chemie, naturwissenschaftliche Laboranalyse (außer MTA)",
        145: "Biochemiker (z.B. klinische Chemie)",
        146: "Chemiker (z.B. klinische Chemie)",
        147: "Humangenetiker",
        148: "Mikrobiologe",
        149: "Dienstleistungen am Menschen (außer medizinische)",
        150: "Körperpflege",
        151: "Fachkraft Beauty und Wellness",
        152: "Friseur",
        153: "Kosmetiker",
        154: "Bestattungswesen",
        155: "Bestattungsfachkraft",
        156: "Berufe aus sonstigen Berufsfeldern",
        157: "Umwelt",
        165: "Jurist",
        169: "Taxifahrer bei Krankentransport",
    },
};
